name: hand_exploration
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_metadata=8.6.1=hd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=14.2.0=h77fa898_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - narwhals=1.31.0=py310h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openssl=3.0.16=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - plotly=6.0.0=py_0
  - python=3.10.15=he870216_1
  - readline=8.2=h5eee18b_0
  - scipy=1.15.2=py310h23a989f_1
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zipp=3.20.2=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.0
      - cycler==0.12.1
      - dash==3.0.4
      - debugpy==1.8.14
      - decorator==4.4.2
      - defusedxml==0.7.1
      - docker-pycreds==0.4.0
      - egl-probe==1.0.2
      - einops==0.8.1
      - executing==2.2.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flask==3.0.3
      - fonttools==4.54.1
      - fqdn==1.5.1
      - fsspec==2024.2.0
      - future==1.0.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gpytorch==1.14
      - grpcio==1.67.0
      - gym==0.23.1
      - gym-notices==0.0.8
      - gymnasium==0.29.0
      - h11==0.16.0
      - h5py==3.12.1
      - hidapi==0.14.0.post2
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.29.0
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.36.0
      - imageio-ffmpeg==0.5.1
      - ipykernel==6.29.5
      - ipython==8.35.0
      - ipywidgets==8.1.6
      - iso8601==2.1.0
      - isoduration==20.11.0
      - itsdangerous==2.2.0
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - jinja2==3.1.3
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.7
      - linear-operator==0.6
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - moviepy==1.0.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.2.1
      - notebook==7.4.1
      - notebook-shim==0.2.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.16.1
      - open3d==0.19.0
      - opencv-python==4.10.0.84
      - orjson==3.10.10
      - overrides==7.7.0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.7
      - prettytable==3.3.0
      - proglog==0.1.10
      - prometheus-client==0.21.1
      - promise==2.3
      - prompt-toolkit==3.0.51
      - protobuf==3.20.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygame==2.1.0
      - pyglet==1.5.29
      - pygments==2.19.1
      - pyparsing==3.2.0
      - pyquaternion==0.9.9
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rl-games==1.6.1
      - robomimic==0.4.0
      - rpds-py==0.24.0
      - rsl-rl==2.0.2
      - rsl-rl-lib==2.2.1
      - safetensors==0.5.2
      - scikit-learn==1.6.0
      - send2trash==1.8.3
      - sentry-sdk==2.17.0
      - setproctitle==1.3.3
      - shortuuid==1.0.13
      - six==1.16.0
      - skrl==1.4.1
      - smmap==5.0.1
      - soupsieve==2.7
      - stable-baselines3==2.3.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tenacity==9.1.2
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensordict==0.5.0
      - termcolor==2.5.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - torch==2.4.0+cu121
      - torchvision==0.19.0
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.49.0
      - trimesh==4.5.1
      - triton==3.1.0
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.9.0
      - tzdata==2024.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - usd-core==24.11
      - wadler-lindig==0.1.5
      - wandb==0.12.21
      - warp-lang==1.6.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.5
      - widgetsnbextension==4.0.14
